import os

DB_HOST = os.getenv('DB_HOST', 'localhost')
UVICORN_HOST = os.getenv('UVICORN_HOST', '127.0.0.1')
AZURE_OPENAI_API_INSTANCE_NAME=os.environ.get('AZURE_OPENAI_API_INSTANCE_NAME','')
AZURE_OPENAI_API_KEY=os.environ.get('AZURE_OPENAI_API_KEY', '')
#AZURE_OPENAI_API_DEPLOYMENT_NAME='gpt-35-turbo-16k'
#AZURE_OPENAI_API_DEPLOYMENT_NAME='gpt-4-turbo'
AZURE_OPENAI_API_DEPLOYMENT_NAME='gpt-35-turbo-1106'
AZURE_OPENAI_API_VERSION='2023-12-01-preview'